# Generated by Django 2.2.3 on 2019-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmeeblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='videos/thumbs/%Y/%m/'),
        ),
    ]
