# Generated by Django 2.2.3 on 2019-08-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmeeblog', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='videos/thumbs/default.jpg', editable=False, upload_to='videos/thumbs/%Y/%m/'),
        ),
    ]
