# Generated by Django 2.2.3 on 2019-08-08 18:37

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmeeblog', '0003_auto_20190803_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmeeblog.Pic'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='promos',
            field=models.ManyToManyField(blank=True, to='mmeeblog.Promo'),
        ),
        migrations.AddField(
            model_name='video',
            name='promos',
            field=models.ManyToManyField(blank=True, to='mmeeblog.Promo'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=audiofield.fields.AudioField(help_text='Allowed type - .mp3, .wav, .ogg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='videos/thumbs/%Y/%m/'),
        ),
    ]
